application: guestbook27
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: .*
  script: guestbook.app

libraries:
- name: webapp2
  version: "2.5.2"
